language: python
# command to install dependencies
install: "make"
# command to run tests
script:
  - make test
cache: pip
jobs:
  include:
    - stage: test
      script:
        - make test
      python: '2.7'
    - stage: test
      script:
        - make test
      python: '3.6'
    - stage: test
      script:
        - make test
      python: '3.7'
      dist: xenial
    - stage: coverage
      python: '3.6'
      script: codecov